CREATE DATABASE IF NOT EXISTS StudentDB;

USE StudentDB;

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    email VARCHAR(50) NOT NULL,
    course VARCHAR(50) NOT NULL
);
